### ISSUE TITLE
Route Fails on Navigation

### ISSUE THREAD

**Issue by stolinski** [AlexxNB/tinro#14]
```
Uncaught (in promise) TypeError: Cannot read property 'c' of undefined
    at transition_out (index.mjs:751)
```

Seems like it's having an issue with this. Not sure if this transition_out is Svelte itself or it is tinro, but it seems to only effect the route when changed client side by clicking a link or using a goto. If you are refreshing the page, the route works just fine.
``` 
function transition_out(block, local, detach, callback) {
    if (block && block.o) {
        if (outroing.has(block))
            return;
        outroing.add(block);
        outros.c.push(() => {
            outroing.delete(block);
            if (callback) {
                if (detach)
                    block.d(1);
                callback();
            }
        });
        block.o(local);
    }
}
```

I realize this might be an odd bug and looks like a possible Svelte issue itself, https://github.com/sveltejs/svelte/issues/3165

Just wanted to let you know this is happening feel free to close.
```
    "svelte": "^3.22.2",
   "tinro": "^0.2.7"
```

**Comment by AlexxNB** [comment]
Can you reproduce this in REPL?

**Comment by stolinski** [comment]
https://github.com/stolinski/bboytools-2040
Is a reproduction, but it's a Meteor app, so I don't think REPL is possible. I totally understand if this is outside your zone, but other Svelte packages have imported and worked fine and wanted to give a heads up because I love your packages's API and would love to find some way to use it.

**Comment by AlexxNB** [comment]
Let's try to import this way:
```javascript
// import {Route} from 'tinro';
import {Route} from 'tinro/cmp/index.js';
```

**Comment by stolinski** [comment]
Perfect. Works as expected. Thank you for your help.

**Comment by jamauro** [comment]
Ran into this same issue. @AlexxNB would you mind adding to the Readme? Not sure if there is something special here in the way Meteor does things.

**Comment by abatros** [comment]
working with tinro@0.6.7
    <script>
    import {router,active,meta} from 'tinro/cmp/index.js';
    const x = meta();
   </script>

ERROR:
Uncaught TypeError: U is not a function
